name: CI/CD for Pyapp

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: [self-hosted, python-app-runner]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Building compose
        run: |
          # Determine which branch variable to use
          if [ "${{ github.ref_name }}" == "main" ]; then
            BRANCH_VAL="${{ vars.ENV_PROD_BRANCH }}"
          else
            BRANCH_VAL="${{ vars.ENV_DEV_BRANCH }}"
          fi
        
          GIT_BRANCH=$BRANCH_VAL docker compose up -d --build
