name: CI/CD for Pyapp

on:
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  run-simulation:
    runs-on: [self-hosted, python-app-runner]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Create .env
        run: |
          if [ "${GITHUB_REF_NAME}" = "dev" ]; then
              echo "${{ secrets.DEV_ENV }}" > .env
          else
              echo "${{ secrets.PROD_ENV }}" > .env
          fi

      - name: Show
        run: cat .env

      - name: Building compose
        run: |
          docker compose -d --build
